name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-test:
    name: Build and test
    strategy:
      matrix:
        runner: [macos-14, ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - uses: actions/checkout@v4
    
    - name: Download libraries
      run: go generate ./...

    - name: Set library environment variables
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          if [ "$RUNNER_ARCH" == "X64" ]; then
            os="linux-amd64"
          elif [ "$RUNNER_ARCH" == "ARM64" ]; then
            os="linux-arm64"
          fi
        elif [ "$RUNNER_OS" == "macOS" ]; then
          os="osx"
        fi
        echo "LIBRARY_PATH=$(pwd)/lib/dynamic/$os:$LIBRARY_PATH" >> $GITHUB_ENV
        if [ "$RUNNER_OS" == "Linux" ]; then
          echo "LD_LIBRARY_PATH=$(pwd)/lib/dynamic/$os:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        elif [ "$RUNNER_OS" == "macOS" ]; then
          echo "DYLD_LIBRARY_PATH=$(pwd)/lib/dynamic/$os:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
        fi

    - name: Build
      run: go build -v

    - name: Test
      run: go test -v
    
    - name: Run example
      working-directory: example
      run: go run main.go

  build-and-test-windows:
    name: Build and test (Windows)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    env:
      GOROOT: /ucrt64/lib/go
      GOPATH: /ucrt64
    steps:
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: UCRT64
        install: >-
          git
          mingw-w64-ucrt-x86_64-go
          mingw-w64-ucrt-x86_64-gcc
          unzip

    - uses: actions/checkout@v4

    - name: Download libraries
      run: go generate ./...

    - name: Set library environment variables
      run: |
        echo "LIBRARY_PATH=$(pwd)/lib/dynamic/windows:$LIBRARY_PATH" >> $GITHUB_ENV

    - name: Build
      run: go build -v

    - name: Test
      run: |
        export PATH="$(pwd)/lib/dynamic/windows:$PATH"
        go test -v

    - name: Run example
      run: |
        export PATH="$(pwd)/lib/dynamic/windows:$PATH"
        cd example
        go run main.go

